const API='https://ddpcbqiiztzgxwkdpszb.supabase.co/functions/v1/marycandys-api';
const $=id=>document.getElementById(id);
const cop=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const setValue=(id,value,text)=>{const el=$(id);el.textContent=text??value;el.classList.toggle('negative',Number(value)<0)};
let state={products:[],sales:[],expenses:[]};
async function api(action,data={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});let j={};try{j=await r.json()}catch{throw new Error('La nube no respondió correctamente')}if(!r.ok||j.error)throw new Error(j.error||'No pudimos guardar. Intenta otra vez.');return j}
async function load(){state=await api('dashboard');render()}
function setBusy(button,busy,label){button.disabled=busy;button.dataset.oldLabel=button.dataset.oldLabel||button.textContent;button.textContent=busy?'Guardando...':(label||button.dataset.oldLabel)}
function setStatus(id,message,type=''){const el=$(id);el.textContent=message;el.className='status'+(type?' '+type:'')}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>{x.classList.remove('active');x.removeAttribute('aria-current')});$(page).classList.add('active');const nav=document.querySelector(`.nav button[data-page="${page}"]`);nav.classList.add('active');nav.setAttribute('aria-current','page');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));document.querySelectorAll('[data-go-home]').forEach(b=>b.addEventListener('click',()=>go('home')));
function render(){const revenue=state.sales.reduce((a,s)=>a+(Number(s.quantity)||0)*(Number(s.unit_price)||0),0),soldCost=state.sales.reduce((a,s)=>a+(Number(s.quantity)||0)*(Number(s.unit_cost)||0),0),expenses=state.expenses.reduce((a,e)=>a+(Number(e.amount)||0),0),gross=revenue-soldCost,net=gross-expenses,investment=state.products.reduce((a,p)=>a+(Number(p.package_cost)||0),0),stock=state.products.reduce((a,p)=>a+(Number(p.stock)||0),0),unitsSold=state.sales.reduce((a,s)=>a+(Number(s.quantity)||0),0),inventoryCost=state.products.reduce((a,p)=>a+(Number(p.stock)||0)*(Number(p.unit_cost)||0),0),inventorySale=state.products.reduce((a,p)=>a+(Number(p.stock)||0)*(Number(p.sale_price)||0),0),potential=inventorySale-inventoryCost,margin=revenue?net/revenue*100:0;
setValue('kInvestment',investment,cop(investment));setValue('kSales',revenue,cop(revenue));setValue('kNet',net,cop(net));setValue('kStock',stock,`${stock} ${stock===1?'dulce':'dulces'}`);setValue('kProducts',state.products.length,String(state.products.length));setValue('kUnits',unitsSold,String(unitsSold));setValue('kPotentialProfit',potential,cop(potential));setValue('aGross',gross,cop(gross));setValue('aExpenses',expenses,cop(expenses));setValue('aNet',net,cop(net));setValue('aMargin',margin,margin.toFixed(1)+'%');setValue('aInvestment',investment,cop(investment));setValue('aInventorySale',inventorySale,cop(inventorySale));setValue('aProducts',state.products.length,String(state.products.length));setValue('aStock',stock,String(stock));
$('productGrid').innerHTML=state.products.map(p=>{const gain=(Number(p.sale_price)||0)-(Number(p.unit_cost)||0);const neg=gain<0?' negative':'';return `<article class="productCard"><div class="productTop"><div class="productName">🍬 ${esc(p.name)}</div><div class="stockPill">Te quedan ${Number(p.stock)||0}</div></div><div class="moneyHero"><span>Lo compraste por</span><b${Number(p.package_cost)<0?' class="negative"':''}>${cop(p.package_cost)}</b></div><div class="miniGrid"><div class="mini"><span>Traía</span><b>${Number(p.units_per_package)||0} dulces</b></div><div class="mini"><span>Cada dulce costó</span><b${Number(p.unit_cost)<0?' class="negative"':''}>${cop(p.unit_cost)}</b></div><div class="mini"><span>Lo vendes por</span><b${Number(p.sale_price)<0?' class="negative"':''}>${cop(p.sale_price)}</b></div><div class="mini good"><span>Ganas por dulce</span><b class="${neg.trim()}">${cop(gain)}</b></div></div></article>`}).join('')||'<div class="empty">🍭 Aún no has agregado productos.</div>';
$('sProduct').innerHTML='<option value="">Elige un dulce...</option>'+state.products.filter(p=>Number(p.stock)>0).map(p=>`<option value="${p.id}">${esc(p.name)} · ${cop(p.sale_price)} · quedan ${p.stock}</option>`).join('');
const sales=state.sales.slice(0,30);$('saleHistory').innerHTML=sales.map(s=>{const qty=Number(s.quantity)||0,total=qty*(Number(s.unit_price)||0),gain=qty*((Number(s.unit_price)||0)-(Number(s.unit_cost)||0));return `<article class="historyItem"><div class="historyHead"><b>🍬 ${esc(s.products?.name||'Producto')}</b><span>${new Date(s.sold_at).toLocaleDateString('es-CO')}</span></div><div class="historyMeta"><div><small>Vendiste</small><b>${qty} ${qty===1?'dulce':'dulces'}</b></div><div><small>Recibiste</small><b${total<0?' class="negative"':''}>${cop(total)}</b></div><div><small>Ganaste</small><b class="${gain<0?'negative':'good'}">${cop(gain)}</b></div><div><small>Precio por dulce</small><b${Number(s.unit_price)<0?' class="negative"':''}>${cop(s.unit_price)}</b></div></div></article>`}).join('')||'<div class="empty">🎉 Tu primera venta aparecerá aquí.</div>';
const ex=state.expenses.slice(0,30);$('expenseHistory').innerHTML=ex.map(e=>`<article class="historyItem"><div class="historyHead"><b>🛍️ ${esc(e.concept)}</b><span>${new Date(e.spent_at).toLocaleDateString('es-CO')}</span></div><div class="historyMeta"><div><small>Pagaste</small><b${Number(e.amount)<0?' class="negative"':''}>${cop(e.amount)}</b></div><div><small>Nota</small><b>${esc(e.notes||'Sin nota')}</b></div></div></article>`).join('')||'<div class="empty">🧾 Aún no has registrado gastos.</div>';
let top={};state.sales.forEach(s=>{const n=s.products?.name||'Producto';top[n]=(top[n]||0)+(Number(s.quantity)||0)});$('topProducts').className='rank'+(Object.keys(top).length?'':' empty');$('topProducts').innerHTML=Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([n,q],i)=>`<p>${['🥇','🥈','🥉','🍬','🍭'][i]} <b>${esc(n)}</b> · ${q} unidades</p>`).join('')||'Aún no hay ventas.';updateSalePreview()}
function calcProduct(){const total=Number($('pCost').value)||0,u=Number($('pUnits').value)||0,unit=u?total/u:0,profit=unit*.30;safePreview('unitCost',unit);safePreview('profit',profit);safePreview('salePrice',unit+profit)}
function safePreview(id,value){const el=$(id);el.textContent=cop(value);el.classList.toggle('negative',Number(value)<0)}
['pCost','pUnits'].forEach(id=>$(id).addEventListener('input',calcProduct));
function selectedProduct(){return state.products.find(p=>String(p.id)===$('sProduct').value)}
function updateSalePreview(){const p=selectedProduct(),qty=Math.max(0,Number($('sQty').value)||0),box=$('salePreview');if(!p||!qty){box.classList.remove('show');return}const receive=qty*(Number(p.sale_price)||0),gain=qty*((Number(p.sale_price)||0)-(Number(p.unit_cost)||0)),left=Math.max(0,(Number(p.stock)||0)-qty);setValue('pvReceive',receive,cop(receive));setValue('pvGain',gain,cop(gain));setValue('pvQty',qty,`${qty} ${qty===1?'dulce':'dulces'}`);setValue('pvStock',left,`${left} ${left===1?'dulce':'dulces'}`);box.classList.add('show')}
$('sProduct').addEventListener('change',updateSalePreview);$('sQty').addEventListener('input',updateSalePreview);
$('productForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('productSubmit'),name=$('pName').value.trim(),cost=Number($('pCost').value),units=Number($('pUnits').value),stock=Number($('pStock').value);setBusy(btn,true);setStatus('productStatus','Guardando tu producto...');try{await api('add_product',{name,package_cost:cost,units_per_package:units,stock});e.target.reset();calcProduct();setStatus('productStatus',`✅ ¡Listo! Invertiste ${cop(cost)} en ${name}.`,'success');await load()}catch(err){setStatus('productStatus','⚠️ '+err.message,'error')}finally{setBusy(btn,false,'🍬 Guardar mi producto')}});
$('saleForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('saleSubmit'),p=selectedProduct(),qty=Number($('sQty').value)||0,notes=$('sNotes').value;if(!p)return;if(qty>Number(p.stock)){setStatus('saleStatus',`⚠️ Solo te quedan ${p.stock} dulces de ${p.name}.`,'error');return}const total=qty*(Number(p.sale_price)||0),gain=qty*((Number(p.sale_price)||0)-(Number(p.unit_cost)||0)),left=(Number(p.stock)||0)-qty;setBusy(btn,true);setStatus('saleStatus','Guardando tu venta...');$('celebrate').classList.remove('show');try{await api('add_sale',{product_id:Number(p.id),quantity:qty,notes});e.target.reset();setStatus('saleStatus','✅ Venta guardada.','success');$('celebrate').innerHTML=`🎉 <strong>¡Muy bien!</strong> Vendiste ${qty} ${qty===1?'dulce':'dulces'}, recibiste ${cop(total)}, ganaste <span class="${gain<0?'negative':''}">${cop(gain)}</span> y te quedan ${left} de ${esc(p.name)}.`;$('celebrate').classList.add('show');await load()}catch(err){setStatus('saleStatus','⚠️ '+err.message,'error')}finally{setBusy(btn,false,'💖 Guardar mi venta')}});
$('expenseForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('expenseSubmit'),concept=$('eConcept').value.trim(),amount=Number($('eAmount').value),notes=$('eNotes').value;setBusy(btn,true);setStatus('expenseStatus','Guardando tu gasto...');try{await api('add_expense',{concept,amount,notes});e.target.reset();setStatus('expenseStatus',`✅ Anotado: pagaste ${cop(amount)} por ${concept}.`,'success');await load()}catch(err){setStatus('expenseStatus','⚠️ '+err.message,'error')}finally{setBusy(btn,false,'🛍️ Guardar mi gasto')}});
load().catch(err=>{document.querySelector('main').insertAdjacentHTML('afterbegin',`<div class="card" role="alert"><strong>☁️ No pudimos conectar con la nube.</strong><p style="margin:8px 0 0;color:var(--muted)">${esc(err.message)}</p></div>`) });